[project]
name = "systems"
version = "0.0.1"
dependencies = [
   "graphviz-hornet",
   "diagrams"
]

[project.optional-dependencies]
dev = [
    "python-lsp-server[all]", "black", "ipython"
    ]

[tool.black]
line-length = 79